### ISSUE TITLE
Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.8

### ISSUE THREAD

**Issue by Reldeam** [GC-spigot/AdvancedTrades#13]
### Describe the bug

When villagers are naturally generated in the game or when they level up I get this error and they don't gain any custom trades:

`18/01/2022 [10:38:42 ERROR: Could not pass event VillagerAcquireTradeEvent to AdvancedTrades v1.0.8]
java.lang.IllegalStateException: null
    at java.util.ArrayList$Itr.remove(ArrayList.java:980) ~[?:?]
    at net.advancedplugins.at.handlers.TradeBuilder.build(TradeBuilder.java:63) ~[AdvancedTrades-1.0.8.jar:?]
    at net.advancedplugins.at.listeners.VillagerTradesPopulator.onVillagerAcquireTradeEvent(VillagerTradesPopulator.java:38) ~[AdvancedTrades-1.0.8.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor86.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-66]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:288) ~[?:?]
    at net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:951) ~[?:?]
    at net.minecraft.world.entity.npc.Villager.increaseMerchantCareer(Villager.java:781) ~[?:?]
    at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:258) ~[?:?]
    at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:245) ~[?:?]
    at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:865) ~[?:?]
    at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3251) ~[?:?]
    at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
    at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
    at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
    at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
    at net.minecraft.world.entity.npc.Villager.tick(Villager.java:290) ~[?:?]
    at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1125) ~[?:?]
    at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
    at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:667) ~[?:?]
    at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.jar:git-Paper-66]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:647) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.jar:git-Paper-66]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-66]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-66]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-66]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-66]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### How to reproduce

1. Spawn villager that should have a custom trade possible.

### Server Log

https://mcpaste.io/c06b4818873db074

**Comment by Reldeam** [comment]
I've turned off all of my plugins except for AdvancedTrades and still got the error.

[log](https://mcpaste.io/45bbc415eb3b61e4)

My ***config.yml*** is default.

**trades.yml**
```
# Configuration file for Villager Trades
# Villagers Professions: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Villager.Profession.html

trades:
  'sand': # Trade name, this can be anything you want
    tradeSettings:
      chance: 25
      requiredVillagerLevel: '2'
      requiredProfession: # Required villager profession, read more at https://trades.advancedplugins.net/trades/professions
        - 'Mason' # If set to none, required profession is disabled
      requiredBiome: # Required villager's biome for this trade, read more at https://trades.advancedplugins.net/trades/biomes
        - 'desert' # If set to none, required profession is disabled
      excludedWorlds: # What worlds should this trade not generate in?
        - 'none'
      maxTradeUses: '16'
    tradeIngredients: # Items required for a trade, read more at https://trades.advancedplugins.net/configuration/items
      # MAXIMUM OF 2 INGREDIENTS PER TRADE!
      '1':
        type: EMERALD
        amount: 1
    tradeResult: # Item which villager will offer in exchange of trade ingredients
      villager:
        experience: '1' # Experience gained by villager with this trade, read more at https://trades.advancedplugins.net/trades/levels
      item: # Item given by villager to player at trade, read more at https://trades.advancedplugins.net/configuration/items
        type: 'SAND'
        amount: 4
  'netherite_scrap': # Trade name, this can be anything you want
    tradeSettings:
      chance: 5
      requiredVillagerLevel: '5'
      requiredProfession: # Required villager profession, read more at https://trades.advancedplugins.net/trades/professions
        - 'Armorer' # If set to none, required profession is disabled
      requiredBiome: # Required villager's biome for this trade, read more at https://trades.advancedplugins.net/trades/biomes
        - 'nether_wastes'
        - 'soul_sand_valley'
        - 'crimson_forest'
        - 'warped_forest'
        - 'basalt_deltas'
      excludedWorlds: # What worlds should this trade not generate in?
        - 'none'
      maxTradeUses: '4'
    tradeIngredients: # Items required for a trade, read more at https://trades.advancedplugins.net/configuration/items
      # MAXIMUM OF 2 INGREDIENTS PER TRADE!
      '1':
        type: EMERALD
        amount: 20
      '2':
        type: NETHER_STAR
        amount: 1
    tradeResult: # Item which villager will offer in exchange of trade ingredients
      villager:
        experience: '5' # Experience gained by villager with this trade, read more at https://trades.advancedplugins.net/trades/levels
      item: # Item given by villager to player at trade, read more at https://trades.advancedplugins.net/configuration/items
        type: 'NETHERITE_SCRAP'
        amount: 2
```
